import { Inter } from "next/font/google";
import "./globals.css";
import { ProductsProvider } from "@/context/productsContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-0 p-0">
        <ProductsProvider>
          {children}
        </ProductsProvider>
      </body>
    </html>
  );
}
